version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos_app
      MYSQL_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
